# Lab 1: Tensor Manipulation


## Imports


In [1]:
import numpy as np
import torch

## Numpy Review

We hope that you are familiar with `numpy` and basic linear algebra.


### 1D Array with Numpy


In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank  of t:', t.ndim)
print('Shape of t:', t.shape)

Rank  of t: 1
Shape of t: (7,)


In [4]:
print('t[0] t[1] t[-1] =', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  =', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     =', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] = 0.0 1.0 6.0
t[2:5] t[4:-1]  = [2. 3. 4.] [4. 5.]
t[:2] t[3:]     = [0. 1.] [3. 4. 5. 6.]


### 2D Array with Numpy


In [5]:
t = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.],
              [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank  of t:', t.ndim)
print('Shape of t:', t.shape)

Rank  of t: 2
Shape of t: (4, 3)


## PyTorch is like Numpy (but better)


### 1D Array with PyTorch


In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1]) # Element
print(t[2:5], t[4:-1])   # Slicing
print(t[:2], t[3:])      # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch


In [10]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [11]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [12]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                        [[13, 14, 15, 16],
                         [17, 18, 19, 20],
                         [21, 22, 23, 24]]]])
print(t)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],

         [[13., 14., 15., 16.],
          [17., 18., 19., 20.],
          [21., 22., 23., 24.]]]])


In [13]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operations in PyTorch

### Mul vs Matmul

In [14]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('Shape of Matrix 1:', m1.shape) # 2 x 2
print('Shape of Matrix 2:', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1, 행렬곱의 결과

m1 = torch.FloatTensor([[1, 2],
                        [3, 4]])
m2 = torch.FloatTensor([[1],
                        [2]])
print('Shape of Matrix 1:', m1.shape) # 2 x 2
print('Shape of Matrix 2:', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # m1 * m2 는 m1.mul(m2)와 같다. 브로드캐스팅 및 elementwise 곱 적용됨됨


-------------
Mul vs Matmul
-------------
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Broadcasting

Carelessly using broadcasting can lead to code hard to debug.


In [15]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1.shape)
print(m2.shape)
print(m1 + m2) # elementwise-sum

torch.Size([1, 2])
torch.Size([1, 2])
tensor([[5., 5.]])


In [16]:
# Vector + Scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # scalar 3 -> [[3, 3]]
print(m1.shape)
print(m2.shape)
print(m1 + m2)

torch.Size([1, 2])
torch.Size([1])
tensor([[4., 5.]])


In [17]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3],
                        [4]])
print(m1.shape)
print(m2.shape)
print(m1 + m2) # 각각 행과 열이 복제(브로드캐스팅)되어 elementwise-sum이 적용됨.

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


### Mean(평균)

In [18]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [19]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2]) 
try:
    print(t.mean())
except Exception as e:
    print(e) # 부동소수점 타입에 대해서만 mean 계산 가능하다. 정수자료형은 불가능

Can only calculate the mean of floating types. Got Long instead.


You can also use `t.mean` for higher rank tensors to get mean of all elements, or mean by particular dimension.

(또한 고차원 rank의 텐서의 모든 요소의 평균값이나 특정한 차원의 평균을 구하기 위해서 `t.mean`을 사용할 수 있다.)

In [20]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.mean()) # Tensor의 모든 요소의 평균값
print(t.mean(dim = 0)) # 행방향 평균 : 각 열에 속하는 요소들의 평균을 취해 행벡터로 만든다.
print(t.mean(dim = 1)) # 열방향 평균 : 각 행에 속하는 요소들의 평균을 취해 열벡터로 만든다.
print(t.mean(dim = -1)) # dim = -1은 dim = 1과 같으므로 dim = 1의 결과와 같다.

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum(합계)


In [24]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
print(t.sum()) # Tensor의 모든 요소의 합
print(t.sum(dim = 0)) # 행방향 합 : 각 열에 속하는 요소들의 합을 취해 행벡터로 만든다.
print(t.sum(dim = 1)) # 열방향 합 : 각 행에 속하는 요소들의 합을 취해 열벡터로 만든다.
print(t.sum(dim = -1)) # dim = -1은 dim = 1과 같다.

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [26]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The `max` operator returns one value if it is called without an argument.

(`max` 연산자는 인자없이 실행된다면 하나의 값을 반환한다.)

In [27]:
print(t.max()) # Returns one value: max

tensor(4.)


The `max` operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

(특정한 차원과 함께 실행될 경우 `max` 연산자는 2개의 값을 반환한다. 첫번째 반환값은 최대값이고, 두번째 반환값은 argmax이다. argmax는 최대값을 갖는 요소의 인덱스를 의미한다.)

In [28]:
print(t.max(dim = 0)) # Returns two values: max and argmax
print('Max:', t.max(dim = 0)[0]) # 행방향 max : 각각의 열에서 max값 추출하여 행벡터로 변환
print('Argmax:', t.max(dim = 0)[1]) # 행방향 argmax : 각각의 열에서 인덱스 1의 값이 max이므로 1, 1 반환


torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max: tensor([3., 4.])
Argmax: tensor([1, 1])


In [29]:
print(t.max(dim = 1))  # 열방향 max : 각각의 행에서 max값 추출하여 열벡터로 변환
print(t.max(dim = -1)) # 2차원이므로 dim = -1은 dim = 1과 같다.

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View

This is a function hard to master, but is very useful!

(숙련되기 어렵지만, 매우 유용한 함수!)

In [30]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [32]:
print(ft.view([-1, 3])) # 2 x 2 x 3 = 12 = ? x 3, ? = 4
print(ft.view([-1, 3]).shape) # 4 x 3

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [34]:
print(ft.view([-1, 1, 3])) # 2 x 2 x 3 = 12 = ? x 1 x 3, ? = 4
print(ft.view([-1, 1, 3]).shape) # 4 x 1 x 3

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [35]:
ft = torch.FloatTensor([[0],
                        [1],
                        [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [36]:
print(ft.squeeze())
print(ft.squeeze().shape) # dimension = 1인 차원이 제거되어 2차원 행렬 -> 1차원 벡터가 됨.

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [37]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [39]:
print(ft.unsqueeze(dim = 0)) # 앞쪽에 차원이 추가됨.
print(ft.unsqueeze(dim = 0).shape) # dim = 0, 0번째 차원에 차원수 1 추가되어 벡터 -> 행렬이 됨.


tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [40]:
print(ft.view(1, -1)) # 1 x ? = 3, ? = 3
print(ft.view(1, -1).shape) # 1 x 3, view로도 차원조정 가능.

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [41]:
print(ft.unsqueeze(dim = 1)) # 뒤쪽에 차원이 추가됨.
print(ft.unsqueeze(dim = 1).shape) # dim = 1, 1번째 차원에 차원수 1 추가되어 벡터 -> 행렬

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [42]:
print(ft.unsqueeze(dim = -1)) # 마찬가지로 뒤쪽에 차원 1 추가
print(ft.unsqueeze(dim = -1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Scatter (for one-hot encoding)

Scatter is a very flexible function. We only discuss how to use it to get a one-hot encoding of indices.

(Scatter는 매우 유연한 함수이다. 여기서는 인덱스의 원-핫 인코딩을 얻기 위해 사용하는 방법만을 다룬다.)

In [43]:
lt = torch.LongTensor([[0],
                       [1],
                       [2],
                       [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [48]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1) # 사용하기 까다로운 함수?
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting


In [49]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [50]:
print(lt.float()) # float 형변환

tensor([1., 2., 3., 4.])


In [51]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [52]:
print(bt.long())  # long 형변환
print(bt.float()) # float 형변환환

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation


In [53]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = torch.FloatTensor([[5, 6],
                       [7, 8]])
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [54]:
print(torch.cat([x, y], dim = 0)) # 행이 추가되도록 쌓음(아래로 쌓음)
print(torch.cat([x, y], dim = 1)) # 열이 추가되도록 쌓음(옆으로 쌓음)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [55]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [56]:
print(torch.stack([x, y, z])) # dim 지정 없는 경우, 자동으로 dim = 0, 행이 추가되도록 쌓음
print(torch.stack([x, y, z], dim = 1)) # 열이 추가되도록 옆으로 쌓음.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [57]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like


In [58]:
x = torch.FloatTensor([[0, 1, 2],
                       [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [59]:
print(torch.ones_like(x))  # x의 shape 유지하며 모두 1로 채운다.
print(torch.zeros_like(x)) # x의 shape 유지하며 모두 0으로 채운다.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [64]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [65]:
print(x.mul(2.))  # elementwise-product by 2
print(x) # 원본 x는 값이 그대로 유지된다.
print(x.mul_(2.)) # elementwise-product by 2
print(x) # 원본 x에 연산결과가 업데이트된다.

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## Miscellaneous

### Zip

In [66]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [67]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
